### PR TITLE
Generate manpages using votca_help2doc

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Review by JensWehner — APPROVED** [review]

**Comment by JensWehner** [comment]
`ModuleNotFoundError: 'xtp_autogen_mapping' requires the 'rdkit' package: https://anaconda.org/conda-forge/rdkit`

**Comment by junghans** [comment]
```
ModuleNotFoundError: 'xtp_autogen_mapping' requires the 'rdkit' package: https://anaconda.org/conda-forge/rdkit
```
Unfortunately openSUSE has no rdkit package!

**Comment by junghans** [comment]
And Fedora removed it in Fedora 34.

**Comment by JensWehner** [comment]
@felipeZ what is the best course of action here?

**Pull request merged**
