### PR TITLE
updated logger and made it cout

### PR DESCRIPTION
**Pull request by JensWehner**
fixes logger output.

### CODE REVIEW

**Comment by JensWehner** [comment]
@votca-bot changelog: improved kmc output

**Comment by junghans** [comment]
[boost.log](https://www.boost.org/doc/libs/1_63_0/libs/log/doc/html/index.html)?

**Comment by baumeier** [comment]
That works. Needs to go to stable too.

**Review by baumeier — APPROVED** [review]

**Comment by JensWehner** [comment]
@junghans yeah would be nice, but I still do not fully understand our logger implementation, there is some multithreading support in it. So I do not want to replace it.

**Comment by JensWehner** [comment]
I guess, we could use boost log

**Pull request merged**
