### PR TITLE
change convergence for davidson

### PR DESCRIPTION
**Pull request by NicoRenaud**
I've cleaned the way we evaluate convergence to address issue #396. It seems to do the job on the minimal example mentioned there :

New Version : 
```
... ... 2020-3-6 17:15:30    0           60 	 3.44e-01 	  0.00% converged
... ... 2020-3-6 17:15:50    1          100 	 7.04e-02 	  0.00% converged
... ... 2020-3-6 17:16:13    2          140 	 3.10e-02 	  0.00% converged
... ... 2020-3-6 17:16:45    3          180 	 3.82e-02 	  0.00% converged
... ... 2020-3-6 17:17:27    4          220 	 1.23e-02 	  0.00% converged
... ... 2020-3-6 17:18:16    5          260 	 5.88e-03 	  0.00% converged
... ... 2020-3-6 17:19:10    6          290 	 1.32e-03 	 33.33% converged
... ... 2020-3-6 17:19:23    7           60 	 1.32e-03 	 60.00% converged
... ... 2020-3-6 17:19:37    8           82 	 1.18e-03 	 60.00% converged
... ... 2020-3-6 17:19:55    9          102 	 4.15e-04 	 66.67% converged
... ... 2020-3-6 17:20:16   10          119 	 1.47e-04 	 73.33% converged
... ... 2020-3-6 17:20:38   11          130 	 5.95e-05 	 86.67% converged
... ... 2020-3-6 17:20:38 Davidson converged after 11 iterations.
```

Old Version : 
```... ... 2020-2-24 21:7:19    0           60      3.44e-01         0.00% converged
... ... 2020-2-24 21:7:27    1          100      7.04e-02         0.00% converged
... ... 2020-2-24 21:7:37    2          140      3.10e-02         0.00% converged
... ... 2020-2-24 21:7:49    3          180      3.82e-02         0.00% converged
... ... 2020-2-24 21:8:5    4          220       1.23e-02         0.00% converged
... ... 2020-2-24 21:8:26    5          260      5.88e-03         0.00% converged
... ... 2020-2-24 21:8:51    6          300      1.31e-03        33.33% converged
... ... 2020-2-24 21:8:58    7           60      2.01e-04        60.00% converged
... ... 2020-2-24 21:9:5    8           82       1.31e-03        96.67% converged
... ... 2020-2-24 21:9:11    9           84      1.25e-03        96.67% converged
... ... 2020-2-24 21:9:18   10           86      9.32e-04        96.67% converged
... ... 2020-2-24 21:9:25   11           88      9.27e-04        100.00% converged
... ... 2020-2-24 21:9:31   12           89      9.26e-04        100.00% converged
... ... 2020-2-24 21:9:38   13           90      9.17e-04        100.00% converged
... ... 2020-2-24 21:9:44   14           91      9.08e-04        100.00% converged
... ... 2020-2-24 21:9:51   15           92      8.89e-04        100.00% converged
... ... 2020-2-24 21:9:58   16           93      8.75e-04        100.00% converged
... ... 2020-2-24 21:10:6   17           94      8.72e-04        100.00% converged
... ... 2020-2-24 21:10:14   18           95     8.67e-04        100.00% converged
... ... 2020-2-24 21:10:22   19           96     8.68e-04        100.00% converged
... ... 2020-2-24 21:10:30   20           97     8.53e-04        100.00% converged
... ... 2020-2-24 21:10:38   21           98     8.53e-04        100.00% converged
... ... 2020-2-24 21:10:47   22           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:10:54   23           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:11:3   24           99      8.51e-04        100.00% converged
... ... 2020-2-24 21:11:10   25           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:11:18   26           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:11:25   27           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:11:33   28           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:11:40   29           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:11:49   30           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:11:59   31           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:12:7   32           99      8.51e-04        100.00% converged
... ... 2020-2-24 21:12:16   33           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:12:25   34           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:12:33   35           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:12:42   36           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:12:51   37           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:13:1   38           99      8.51e-04        100.00% converged
... ... 2020-2-24 21:13:9   39           99      8.51e-04        100.00% converged
... ... 2020-2-24 21:13:19   40           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:13:29   41           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:13:39   42           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:13:50   43           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:13:59   44           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:14:8   45           99      8.51e-04        100.00% converged
... ... 2020-2-24 21:14:16   46           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:14:24   47           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:14:32   48           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:14:39   49           99     8.51e-04        100.00% converged
... ... 2020-2-24 21:14:39- Warning : Davidson  1.00% converged after 49 iterations
```

@JavierSijen could you test it on larger example ?

### CODE REVIEW

**Comment by NicoRenaud** [comment]
The last commit makes sure that the iteration information is displayed after calculation of the residue norms. Hence we go nicely to 100% converged

**Comment by JavierSijen** [comment]
I redid all my benchmarks using the fix branch (16 molecules, 8 variations). In all cases, Davidson converged!

Below are some benchmarking results.

benchmarks

**Comment by JensWehner** [comment]
nice thanks

**Comment by NicoRenaud** [comment]
@JavierSijen thank for the test ! It doesn't look too bad to me ! @Jens thanks for fixing your own requested changes :) It's all good for me for now

**Pull request merged**
