### PR TITLE
should add electron when occ != 0

### PR DESCRIPTION
**Pull request by mbarbry**
I think I caught an error in the nwchem parser.
The parser adds electron only if the occupation number is equal to two. But I generated calculations were these numbers were equal to one. Checking with the main log file, it thus makes sense to me that electrons should be counted if the occupation number is different than 0.

But I don't know so well nwchem, it should be checked.

### CODE REVIEW

**Comment by JensWehner** [comment]
I agree, but for this we have to extend our whole infrastructure for open shell systems and till then I ll wait

**Comment by baumeier** [comment]
Just to confirm:  When you run a closed shell system, things are working as they should?

If this occurs for open-shell calculations, I agree with @JensWehner to wait until we have proper structures to read MO energies and coefficients into.

**Comment by baumeier** [comment]
Basically needs to be addressed with #6

**Comment by junghans** [comment]
Needs update!

**Comment by JensWehner** [comment]
as it is on the feature list, this will be closed for the moment

**Pull request closed without merging**
