### PR TITLE
introduced hdf5 header and checked for Ubuntu's gcc-9

### PR DESCRIPTION
**Pull request by JensWehner**
should fix https://github.com/votca/xtp/issues/436

### CODE REVIEW

**Comment by JensWehner** [comment]
argh one stupid `update branch`

**Comment by junghans** [comment]
Let me do a rebase!

**Comment by JensWehner** [comment]
thx

**Comment by junghans** [comment]
@JensWehner ubuntu is still failing.

**Comment by JensWehner** [comment]
yeah

**Comment by junghans** [comment]
Closing in favor of #438

**Pull request closed without merging**
