### PR TITLE
Correct total energy in QMMM with QP

### LINKED ISSUE #590: Total energy in QMMM with quasiparticle states
If a QMMM calculation is performed for `dqp` quasiparticle states, the total energy reported for the qm region is just the QP energy, while it should be `EDFT - eps_qp` for occupied and `EDFT + eps_qp` for unoccupied QP states.

### PR DESCRIPTION
**Pull request by baumeier**
Fixes #590

### CODE REVIEW

**Review by JensWehner — APPROVED** [review]
Good point

**Comment by baumeier** [comment]
@JensWehner Can you make sense of the failed fedora build?

**Comment by JensWehner** [comment]
@baumeier I have seen it before. I think fedora is a bit unstable atm. Last time I restarted the build and it worked.

@junghans any idea?

**Comment by junghans** [comment]
What was the error?

**Comment by JensWehner** [comment]
clang-11 failed to link

**Comment by JensWehner** [comment]
`clang-11: error: unable to execute command: Segmentation fault (core dumped)
clang-11: error: linker command failed due to signal (use -v to see invocation)
[397/576] /usr/lib64/ccache/clang++  -I/__w/xtp/xtp/votca/xtp/include -Ixtp/include -Ixtp/include/votca/xtp -I/__w/xtp/xtp/votca/csg/include -I/__w/xtp/xtp/votca/tools/include -Itools/include -Itools/include/votca/tools -isystem /usr/include/eigen3 -Wall -Wextra -Wpedantic -Wshadow -Wconversion -Wno-sign-conversion -Werror -Wno-deprecated-copy -O2 -DNDEBUG -fopenmp=libomp -std=c++14 -MD -MT xtp/src/tools/CMakeFiles/xtp_map.dir/xtp_map.cc.o -MF xtp/src/tools/CMakeFiles/xtp_map.dir/xtp_map.cc.o.d -o xtp/src/tools/CMakeFiles/xtp_map.dir/xtp_map.cc.o -c /__w/xtp/xtp/votca/xtp/src/tools/xtp_map.cc`

**Comment by baumeier** [comment]
@votca-bot format

**Comment by junghans** [comment]
If it is on rawhide, just ignore it for now, they had some bug in binutils package.

**Comment by junghans** [comment]
Updated the rawhide image, it should be fixed now.

**Pull request merged**
