### PR TITLE
Switch to unique ptr for molecules stored in csg topology class. 

### PR DESCRIPTION
**Pull request by JoshuaSBrown**
This is connected to https://github.com/votca/csg/pull/657

### CODE REVIEW

**Review by JensWehner — APPROVED** [review]

**Comment by junghans** [comment]
@JoshuaSBrown 
```
home/votca/votca/xtp/src/tools/xtp_map.cc:163:55: error: cannot convert 'std::unique_ptr<votca::csg::Molecule>' to 'const votca::csg::Molecule*' in initialization
  163 |     for (const CSG::Molecule* mol : mdtopol.Molecules()) {
      |                                                       
```

**Comment by junghans** [comment]
@JensWehner / @JoshuaSBrown 
from votca/votca#628:
```
FAILED: xtp/src/libxtp/CMakeFiles/votca_xtp.dir/md2qmengine.cc.o 
/usr/lib64/ccache/clang++ -Dvotca_xtp_EXPORTS -Ixtp/src/libxtp -I../xtp/src/libxtp -I../xtp/include -Ixtp/include -Ixtp/include/votca/xtp -I../csg/include -I../tools/include -Itools/include -Itools/include/votca/tools -isystem /usr/include/eigen3 -isystem /usr/include/libint2 -isystem /usr/include/libecpint -Wall -Wextra -Wpedantic -Wshadow -Wconversion -Wno-sign-conversion -Werror -Wno-deprecated-copy -O2 -DNDEBUG -fPIC -fopenmp=libomp -std=c++14 -MD -MT xtp/src/libxtp/CMakeFiles/votca_xtp.dir/md2qmengine.cc.o -MF xtp/src/libxtp/CMakeFiles/votca_xtp.dir/md2qmengine.cc.o.d -o xtp/src/libxtp/CMakeFiles/votca_xtp.dir/md2qmengine.cc.o -c ../xtp/src/libxtp/md2qmengine.cc
../xtp/src/libxtp/md2qmengine.cc:200:36: error: no member named 'get' in 'votca::csg::Molecule'
        DetermineAtomNumOffset(mol.get(), MolToAtomIds[mol.getName()]);
                               ~~~ ^
1 error generated.
```

**Comment by junghans** [comment]
ping @JoshuaSBrown

**Comment by junghans** [comment]
@JoshuaSBrown still:
```
2021-02-18T16:15:58.3527286Z cd /__w/votca/votca/builddir/xtp/src/tools && /usr/bin/cmake -E cmake_link_script CMakeFiles/xtp_run.dir/link.txt --verbose=1
2021-02-18T16:15:58.3611931Z /usr/lib64/ccache/g++  -Wall -Wextra -Wpedantic -Wshadow -Wconversion -Werror -Wno-deprecated-copy -O2 -DNDEBUG CMakeFiles/xtp_run.dir/xtp_run.cc.o -o xtp_run  -Wl,-rpath,/__w/votca/votca/builddir/xtp/src/libxtp:/__w/votca/votca/builddir/csg/src/libcsg:/__w/votca/votca/builddir/tools/src/libtools: ../libxtp/libvotca_xtp.so.2022 ../../../csg/src/libcsg/libvotca_csg.so.2022 ../../../tools/src/libtools/libvotca_tools.so.2022 /usr/lib64/libboost_program_options.so /usr/lib64/libfftw3.so /usr/lib64/libhdf5_cpp.so /usr/lib64/libhdf5.so /usr/lib/gcc/x86_64-redhat-linux/10/libgomp.so /usr/lib64/libpthread.so 
2021-02-18T16:15:58.4471305Z /__w/votca/votca/xtp/src/tools/xtp_map.cc: In member function 'virtual void XtpMap::Run()':
2021-02-18T16:15:58.4472184Z /__w/votca/votca/xtp/src/tools/xtp_map.cc:161:16: error: 'csg' does not name a type
2021-02-18T16:15:58.4472836Z   161 |     for (const csg::Molecule& mol : mdtopol.Molecules()) {
2021-02-18T16:15:58.4473269Z       |                ^~~
2021-02-18T16:15:58.4473878Z /__w/votca/votca/xtp/src/tools/xtp_map.cc:166:6: error: expected ';' before 'for'
2021-02-18T16:15:58.4474319Z   166 |     }
2021-02-18T16:15:58.4474607Z       |      ^
2021-02-18T16:15:58.4474861Z       |      ;
```

**Comment by junghans** [comment]
ping @JensWehner

**Comment by junghans** [comment]
Please use the `molecules_to_unique_ptr` branch in `votca/votca`.

**Review by JensWehner — APPROVED** [review]
Nice

**Pull request merged**
