### PR TITLE
Unit test rework

### PR DESCRIPTION
**Pull request by JensWehner**
Like in tools and csg large matrices and other larger files are not stored in the source code anymore but instead are read in from files to reduce compile times.

### CODE REVIEW

**Comment by JensWehner** [comment]
@junghans please review! I deleted the large memory test thing, because the compilation of the test should not require large memory anymore, because everything is done at runtime.

**Comment by JensWehner** [comment]
please do not delete branch, after merging because there are more tests to refactor but I think this already warrants a merge.

**Comment by JensWehner** [comment]
@votca-bot changelog: Unittests can read input and reference values from files

**Comment by JensWehner** [comment]
@votca-bot format

**Comment by rubengerritsen** [comment]
@votca-bot format

**Comment by rubengerritsen** [comment]
@votca-bot format

**Pull request merged**
