### PR TITLE
Removed unnecessary elements.h file as it is in tools

### PR DESCRIPTION
**Pull request by JoshuaSBrown**
This file was never used in xtp and is also present in tools

### CODE REVIEW

**Comment by JoshuaSBrown** [comment]
I don't think anything uses it.

**Comment by JoshuaSBrown** [comment]
It builds but wait for the tests to finish.

**Comment by junghans** [comment]
Would it be better to merge #109 and then merge master back into `development`.

**Comment by JoshuaSBrown** [comment]
I'm not a git master... so I'll do whatever you think is a good idea, but I think the development branch is now quite different from the master in some ways so there will be extra stuff that needs to be done. (maybe)

**Comment by JoshuaSBrown** [comment]
@JensWehner ya it didn't build...

**Comment by junghans** [comment]
In a nutshell, if you have to do a commit twice, you are doing something wrong! Just add it one branch and merge it into the other. So here, add it to `master` and then merge `master` into `development`.

**Comment by JensWehner** [comment]
Dismissed because of master merge

**Pull request closed without merging**
