### PR TITLE
Script for automatic generation of mapping file, optimized XYZ/MPS files, reorg/exc energies

### PR DESCRIPTION
**Pull request by baumeier**
This adds a Python tool `xtp_autogen_mapping` to create a `mapping.xml` file and optionally all required `XYZ` and `MPS` files from a single molecule `PDB` file taken from the MD frame.

**Requires:**
- [rdkit](https://github.com/rdkit/rdkit) 

**Implementation:**
- `rdkit` detects so-called *rotatable bonds* and provides functionality to fragment a molecule at these bonds
- fragments maps are written to `mapping.xml`
- optionally can call `orca` to optimize geometries for the `segment` with DFT, get CHELPG charges, and optimize atomic polarizabilities, then copies these files to `QC_FILES` and `MP_FILES`, adds energies to `mapping.xml`

**TODO:**
- [x] auto generate a `localframe`
- [x] check definitions/units of the energies 
- [x] clean up the python code 
- [x] extract names from MD?
- [ ] several single molecule PDB files for mixtures

**Usage examples:**

1. `xtp_autogen_mapping -pdb CO.pdb -opt 1` generates mapping file including all optimizations
```
<?xml version="1.0" ?>
<topology>
   <molecules>
      <molecule>
         <name>CO</name>
         <mdname>CO</mdname>
         <segments>
            <segment>
               <name>CO</name>
               <qmcoords_n>QC_FILES/CO_n.xyz</qmcoords_n>
               <multipoles_n>MP_FILES/CO_n_polar.mps</multipoles_n>
               <qmcoords_h>QC_FILES/CO_h.xyz</qmcoords_h>
               <multipoles_h>MP_FILES/CO_h_polar.mps</multipoles_h>
               <U_xX_nN_h>13.964892558401951</U_xX_nN_h>
               <U_nX_nN_h>0.01894740313436599</U_nX_nN_h>
               <U_xN_xX_h>0.020035420475801376</U_xN_xX_h>
               <qmcoords_e>QC_FILES/CO_e.xyz</qmcoords_e>
               <multipoles_e>MP_FILES/CO_e_polar.mps</multipoles_e>
               <U_xX_nN_e>1.7572562628603443</U_xX_nN_e>
               <U_nX_nN_e>0.42110860883007717</U_nX_nN_e>
               <U_xN_xX_e>0.36700622312803216</U_xN_xX_e>
               <map2md>0</map2md>
               <fragments>
                  <fragment>
                     <name>fragment1</name>
                     <mdatoms>0:C:0 0:O:1 </mdatoms>
                     <qmatoms>0:C 1:O </qmatoms>
                     <mpoles>0:C 1:O </mpoles>
                     <weights>12.011 15.999 </weights>
                     <localframe/>
                  </fragment>
               </fragments>
            </segment>
         </segments>
      </molecule>
   </molecules>
</topology>
```
2. `xtp_autogen_mapping -pdb NPB.pdb` generates mapping with fragments only 
bitmap
```
<?xml version="1.0" ?>
<topology>
   <molecules>
      <molecule>
         <name>NPB</name>
         <mdname>NPB</mdname>
         <segments>
            <segment>
               <name>NPB</name>
               <qmcoords_n>QC_FILES/NPB_n.xyz</qmcoords_n>
               <multipoles_n>MP_FILES/NPB_n_polar.mps</multipoles_n>
               <qmcoords_h>QC_FILES/NPB_h.xyz</qmcoords_h>
               <multipoles_h>MP_FILES/NPB_h_polar.mps</multipoles_h>
               <fragments>
                  <fragment>
                     <name>fragment1</name>
                     <mdatoms>0:N:0 </mdatoms>
                     <qmatoms>0:N </qmatoms>
                     <mpoles>0:N </mpoles>
                     <weights>14.007 </weights>
                     <localframe/>
                  </fragment>
                  <fragment>
                     <name>fragment2</name>
                     <mdatoms>0:C:1 0:C1:2 0:C2:4 0:C3:5 0:C4:6 0:C5:7 0:H:46 0:H1:47 0:H2:48 0:H3:49 </mdatoms>
                     <qmatoms>1:C 2:C 4:C 5:C 6:C 7:C 46:H 47:H 48:H 49:H </qmatoms>
                     <mpoles>1:C 2:C 4:C 5:C 6:C 7:C 46:H 47:H 48:H 49:H </mpoles>
                     <weights>12.011 12.011 12.011 12.011 12.011 12.011 1.008 1.008 1.008 1.008 </weights>
                     <localframe/>
                  </fragment>
                  <fragment>
                     <name>fragment3</name>
                     <mdatoms>0:N1:3 </mdatoms>
                     <qmatoms>3:N </qmatoms>
                     <mpoles>3:N </mpoles>
                     <weights>14.007 </weights>
                     <localframe/>
                  </fragment>
                  <fragment>
                     <name>fragment4</name>
                     <mdatoms>0:C6:8 0:C7:9 0:C8:10 0:C9:11 0:C10:12 0:C11:13 0:H4:50 0:H5:51 0:H6:52 0:H7:53 </mdatoms>
                     <qmatoms>8:C 9:C 10:C 11:C 12:C 13:C 50:H 51:H 52:H 53:H </qmatoms>
                     <mpoles>8:C 9:C 10:C 11:C 12:C 13:C 50:H 51:H 52:H 53:H </mpoles>
                     <weights>12.011 12.011 12.011 12.011 12.011 12.011 1.008 1.008 1.008 1.008 </weights>
                     <localframe/>
                  </fragment>
                  <fragment>
                     <name>fragment5</name>
                     <mdatoms>0:C12:14 0:C13:15 0:C14:16 0:C15:17 0:C16:18 0:C17:19 0:C40:42 0:C41:43 0:C42:44 0:C43:45 0:H8:54 0:H9:55 0:H10:56 0:H28:74 0:H29:75 0:H30:76 0:H31:77 </mdatoms>
                     <qmatoms>14:C 15:C 16:C 17:C 18:C 19:C 42:C 43:C 44:C 45:C 54:H 55:H 56:H 74:H 75:H 76:H 77:H </qmatoms>
                     <mpoles>14:C 15:C 16:C 17:C 18:C 19:C 42:C 43:C 44:C 45:C 54:H 55:H 56:H 74:H 75:H 76:H 77:H </mpoles>
                     <weights>12.011 12.011 12.011 12.011 12.011 12.011 12.011 12.011 12.011 12.011 1.008 1.008 1.008 1.008 1.008 1.008 1.008 </weights>
                     <localframe/>
                  </fragment>
                  <fragment>
                     <name>fragment6</name>
                     <mdatoms>0:C18:20 0:C19:21 0:C20:22 0:C21:23 0:C22:24 0:C23:25 0:H11:57 0:H12:58 0:H13:59 0:H14:60 0:H15:61 </mdatoms>
                     <qmatoms>20:C 21:C 22:C 23:C 24:C 25:C 57:H 58:H 59:H 60:H 61:H </qmatoms>
                     <mpoles>20:C 21:C 22:C 23:C 24:C 25:C 57:H 58:H 59:H 60:H 61:H </mpoles>
                     <weights>12.011 12.011 12.011 12.011 12.011 12.011 1.008 1.008 1.008 1.008 1.008 </weights>
                     <localframe/>
                  </fragment>
                  <fragment>
                     <name>fragment7</name>
                     <mdatoms>0:C24:26 0:C25:27 0:C26:28 0:C27:29 0:C28:30 0:C29:31 0:H16:62 0:H17:63 0:H18:64 0:H19:65 0:H20:66 </mdatoms>
                     <qmatoms>26:C 27:C 28:C 29:C 30:C 31:C 62:H 63:H 64:H 65:H 66:H </qmatoms>
                     <mpoles>26:C 27:C 28:C 29:C 30:C 31:C 62:H 63:H 64:H 65:H 66:H </mpoles>
                     <weights>12.011 12.011 12.011 12.011 12.011 12.011 1.008 1.008 1.008 1.008 1.008 </weights>
                     <localframe/>
                  </fragment>
                  <fragment>
                     <name>fragment8</name>
                     <mdatoms>0:C30:32 0:C31:33 0:C32:34 0:C33:35 0:C34:36 0:C35:37 0:C36:38 0:C37:39 0:C38:40 0:C39:41 0:H21:67 0:H22:68 0:H23:69 0:H24:70 0:H25:71 0:H26:72 0:H27:73 </mdatoms>
                     <qmatoms>32:C 33:C 34:C 35:C 36:C 37:C 38:C 39:C 40:C 41:C 67:H 68:H 69:H 70:H 71:H 72:H 73:H </qmatoms>
                     <mpoles>32:C 33:C 34:C 35:C 36:C 37:C 38:C 39:C 40:C 41:C 67:H 68:H 69:H 70:H 71:H 72:H 73:H </mpoles>
                     <weights>12.011 12.011 12.011 12.011 12.011 12.011 12.011 12.011 12.011 12.011 1.008 1.008 1.008 1.008 1.008 1.008 1.008 </weights>
                     <localframe/>
                  </fragment>
               </fragments>
            </segment>
         </segments>
      </molecule>
   </molecules>
</topology>
```

### CODE REVIEW

**Comment by baumeier** [comment]
@felipeZ @JensWehner @rubengerritsen @gtirimbo This is super useful but the script needs obvious polishing. Would be good if someone of you could have a look.

**Comment by JoshuaSBrown** [comment]
Wow this is really neat, I had hoped to help get this directly implemented in VOTCA but alas I don't have the time I used too.

**Comment by felipeZ** [comment]
@baumeier  I will take care of polishing the Python script. Is it there some minimal test/example that I can run to be sure that I don't break anything during the refactoring?

**Comment by gtirimbo** [comment]
@baumeier I see you already included my suggestion for taking into account the MD names. Don't know if you meant something different in the TODO list.
I am working on the localframe automatic selection.

**Comment by baumeier** [comment]
@gtirimbo I was thinking about the molecule and segment `mdname` and `name`. I think the former needs to correspond to the name in the topology (at least in Gromacs), and we can just make a note that one has to specify it instead of parsing it from `topol.top` or so (not sure how it works in LAMMPS).

**Comment by baumeier** [comment]
We probably should add some output telling the user what stage the script is working on. Especially the optimizations take some time and it may be instructive.

Also maybe a disclaimer of some sort that - as of now - the full automation is only reasonable for non-polymeric systems, and molecules without long side-chains. Because those will be included in the segment and therefore included in the optimizations, which is useless.

**Comment by felipeZ** [comment]
@baumeier  Shall we perform an optimization using a UFF (or something else) before calling Orca. This preoptimization can potentially speed up the optimization.

**Comment by baumeier** [comment]
@felipeZ It may be useful since the starting PDB is supposedly taken from the MD sim and might therefore be a bit far from the minimum. Can give it a shot. Curious what those two lines are.

**Comment by JensWehner** [comment]
in LAMMPS the mdname is created I think from the element and the id, @JoshuaSBrown knows the most I think.

**Comment by baumeier** [comment]
> in LAMMPS the mdname is created I think from the element and the id, @JoshuaSBrown knows the most I think.

We are talking about the `mdname` of the molecule/segment and not the atom.

**Comment by felipeZ** [comment]
> @felipeZ It may be useful since the starting PDB is supposedly taken from the MD sim and might therefore be a bit far from the minimum. Can give it a shot. Curious what those two lines are.

@baumeier  using the `CO.pdb` file that you have in the example, the optiimization can be done like:
```python
from rdkit import Chem
from rdkit.Chem import AllChem

mol = Chem.MolFromPDBFile("CO.pdb", removeHs=False)
AllChem.EmbedMolecule(mol)
AllChem.UFFOptimizeMolecule(mol)

**Comment by JoshuaSBrown** [comment]
> > in LAMMPS the mdname is created I think from the element and the id, @JoshuaSBrown knows the most I think.

No, the the molecule name is created from the element name and the number of elements of that type sorted in alphabetical order. E.g. water would be H2O1. This could of course be changed if it becomes a problem.

**Comment by baumeier** [comment]
@felipeZ We should still add options to the command to specify functional, basis set, and whether or not to use RI, then pass this through to the orca call.

**Comment by felipeZ** [comment]
> @felipeZ We should still add options to the command to specify functional, basis set, and whether or not to use RI, then pass this through to the orca call.

I am going to do so

**Comment by felipeZ** [comment]
@baumeier I have added the command line options for the functional, basisset and RI. Just notice that the RI options is called `--nori` meaning that by default the RI is set to true unless that the user passes the flag `--nori`

**Comment by baumeier** [comment]
@felipeZ I added an automatic molecule name as used in our LAMMPS reade, an option to specify the name from the command line, and a warning if GROMACS is used and no name given.

Looks all good now. One point still left from the list, but we could also postpone this to later?

**Comment by felipeZ** [comment]
> @felipeZ I added an automatic molecule name as used in our LAMMPS reade, an option to specify the name from the command line, and a warning if GROMACS is used and no name given.
> 
> Looks all good now. One point still left from the list, but we could also postpone this to later?
@baumeier  It seems also good for me. I am going to change a couple of syntactic things and I will be happy :)

**Review by felipeZ — APPROVED** [review]
This tools lowers significantly the entry barrier for people wanting to use the code.
Great Job!

**Pull request merged**
