### PR TITLE
refactored tables to not have to use dummy elements anymore

### PR DESCRIPTION
**Pull request by JensWehner**
Now the `setupCptTable` is a static method of each class, which separates layout and writing data better. 

@pmadhikar just if you are curious still.

### CODE REVIEW

**Comment by JensWehner** [comment]
@votca-bot format

**Comment by JensWehner** [comment]
@votca-bot changelog: Made SetupCptTable static

**Review by rubengerritsen — APPROVED** [review]
Nice

**Comment by pmadhikar** [comment]
Good idea!

**Review by pmadhikar — COMMENTED** [review]
Smart idea.

**Comment by JensWehner** [comment]
Yeah, it is not as generalizable, but you do not have to carry the dummy argument around.

**Pull request merged**
