### PR TITLE
Clean scripts

### LINKED ISSUE #668: clean and fix scripts
## Proposed changes
* Remove unused scripts
* Clean and remove Python2 syntax
* Remove `make_auxbasis` script
* Improve readability

### PR DESCRIPTION
**Pull request by felipeZ**
Fix #668

### CODE REVIEW

**Review by junghans — CHANGES_REQUESTED** [review]
Remove the script from rst doc, too.

**Review by JensWehner — APPROVED** [review]

**Comment by felipeZ** [comment]
@JensWehner  the `basisset` scripts needs some refactoring to remove all the nested `for/if` loops. I don't know exactly what is the expected behaviour of the script so I am leaving it like that, but maybe you can have a look.

**Comment by junghans** [comment]
> Solve #668

@felipeZ the magic github keyword is "Fix", not "Solve".

**Review by junghans — APPROVED** [review]

**Comment by felipeZ** [comment]
> > Solve #668
> 
> @felipeZ the magic github keyword is "Fix", not "Solve".

Thanks for let me know! I confused them all the time

**Pull request merged**
