### PR TITLE
GHA: add Debug build

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Review by JensWehner — APPROVED** [review]

**Comment by junghans** [comment]
@certik

**Comment by certik** [comment]
Cool, the Docker image seems to install in 5min. It's not actually using the Intel compiler, right? Only MKL?

https://github.com/votca/votca/runs/1337056446

**Comment by junghans** [comment]
We haven't update the `votca/votca` repo yet, it uses intel e.g. here: https://github.com/votca/xtp/runs/1371280882?check_suite_focus=true

**Comment by certik** [comment]
@junghans thank you! This is really useful. How do you install the trial license? I don't see it in the log.

**Pull request merged**
