### PR TITLE
added more checks to the dft_parse_part

### PR DESCRIPTION
**Pull request by JensWehner**
@baumeier can you check if this fixes https://github.com/votca/xtp/issues/507

### CODE REVIEW

**Comment by JensWehner** [comment]
@baumeier ping

**Comment by junghans** [comment]
@votca-bot changelog: add more checks to the dft_parse_part

**Comment by baumeier** [comment]
@junghans I think this should also go into a fix for stable, can that be done?

**Comment by junghans** [comment]
Sure please make a pull request into `stable` .

**Pull request merged**
