### PR TITLE
Remove Kokkos from XTP

### PR DESCRIPTION
**Pull request by rubengerritsen**
The Kokkos based ewald implementation is now archived on the branch `oldKokkosEwald`. 
This PR removes the Kokkos dependent source code and the cmake parts that search for Kokkos.

### CODE REVIEW

**Comment by rubengerritsen** [comment]
@votca-bot changelog: remove kokkos dependent ewald

**Review by junghans — APPROVED** [review]
Do we need to update the NOTICE file?

**Review by JensWehner — CHANGES_REQUESTED** [review]
Thanks for the change. I think we should modify the NOTICE file and acknowledge their help when the new ewald is ready @baumeier ?

**Comment by baumeier** [comment]
> Thanks for the change. I think we should modify the NOTICE file and acknowledge their help when the new ewald is ready @baumeier ?

Agreed.

**Review by JensWehner — APPROVED** [review]

**Pull request merged**
