### PR TITLE
made the choice of sigma a factory

### PR DESCRIPTION
**Pull request by JensWehner**
Made the construction of sigma a factory to make it look nicer. 

blocked by https://github.com/votca/tools/pull/377

### CODE REVIEW

**Comment by JensWehner** [comment]
@votca-bot format

**Comment by JensWehner** [comment]
@votca-bot changelog: sigma choices put into a factory

**Comment by junghans** [comment]
Needs a retrigger!

**Comment by junghans** [comment]
@votca-bot copyright

**Review by junghans — APPROVED** [review]

**Comment by junghans** [comment]
@JensWehner 
```
unknown location(0): fatal error: in "CudaPipeline_test/matmul_AbB": std::runtime_error: CUDA Runtime Error: system has unsupported display driver / cuda driver combination
```

**Comment by JensWehner** [comment]
yes, someone or something must have updated the runner, I have a look tomorrow.

**Pull request merged**
